version: '3.9'
services:
    app:
        build: .
        container_name: dump-postgres-app
        env_file:
            - .env
        ports:
            - '${APP_PORT:-8080}:8080'
        volumes:
            - ./backups:/app/backups
        restart: unless-stopped
